### ISSUE TITLE
Getting `undefined symbol: __aarch64_ldadd4_acq_rel` when running in docker container

### ISSUE THREAD

**Issue by dsclassen** [jbhopkins/bioxtasraw#4]
This may or may not be a bioxtasraw issue, but I'm at a bit of a lose on how to fix this.... or even what the problem is.

This is the error:

```python
>>> import bioxtasraw.RAWAPI as raw
dlopen("/home/app/.cache/pocl/kcache/BE/BJKPFDOLMJHLOMHFOOHOPFAFADFHBADNAHCNP/check_atomic32/0-0-0/check_atomic32.so") failed with '/home/app/.cache/pocl/kcache/BE/BJKPFDOLMJHLOMHFOOHOPFAFADFHBADNAHCNP/check_atomic32/0-0-0/check_atomic32.so: undefined symbol: __aarch64_ldadd4_acq_rel'.
note: missing symbols in the kernel binary might be reported as 'file not found' errors.
Aborted
```

Background:

I am attempting to build a Docker image that includes Miniconda3 and the BioXTAS command line tools (no GUI needed). I am developing on an M3 Apple machine within Docker Desktop. The Docker builder supports these architectures:

```
arm64
amd64
amd64/v2
riscv64
ppc64le
s390x
386
mips64le
mips64
arm/v7
arm/v6
```

This is the list of packages that I install before building BioXTAS:

```
dependencies:
  - pocl
  - pillow
  - six
  - wheel
  - numpy
  - scipy
  - matplotlib
  - python-igraph
  - numba
  - h5py
  - cython
  - numexpr
  - reportlab
  - dbus-python
  - fabio
  - pyfai
  - hdf5plugin
  - mmcif_pdbx
  - svglib
  - libmamba
 ```

and this is a snippet from the Dockerfile if you're interested:

```
RUN apt-get update && \
    apt-get install -y zip build-essential libarchive13

# Copy the source ZIP file
COPY bioxtas/bioxtasraw-2.2.2.zip /tmp/bioxtasraw-2.2.2.zip

# Install BioXYAS from source
WORKDIR /tmp
RUN unzip bioxtasraw-2.2.2.zip && \
    cd bioxtasraw-2.2.2 && \
    python3 setup.py build_ext --inplace && \
    pip3 install . && \
    cd .. && \
    rm bioxtasraw-2.2.2.zip && \
    rm -rf bioxtasraw-2.2.2
```

**Comment by dsclassen** [comment]
If I leave out the `pocl` dependency I get a slightly different error:

```python
>>> import bioxtasraw.RAWAPI as raw
WARNING:silx.opencl.common:The module pyOpenCL has been imported but can't be used here
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniforge3/lib/python3.10/site-packages/bioxtasraw/RAWAPI.py", line 63, in <module>
    import bioxtasraw.DENSS as DENSS
  File "/miniforge3/lib/python3.10/site-packages/bioxtasraw/DENSS.py", line 62, in <module>
    import bioxtasraw.denss_resources.resources as resources
ModuleNotFoundError: No module named 'bioxtasraw.denss_resources'
```

**Comment by jbhopkins** [comment]
Hi Scott,

The first error seems to be related to pocl, which is apparently by your second comment. So I don't think that's a RAW issue. I'd recommend you touch base with those folks on the first one. I'd guess you could make a simple test case by just importing pocl, rather than the RAW API (I think pocl in this case is being imported through pyFAI).

The second error is RAW related. The first thing to do is verify that the bioxtasraw/bioxtasraw/denss_resources folder exists in the version of RAW that you're trying to install. I just checked and it is in the zip that is distributed from sourceforge, but maybe it didn't get copied into your docker image or something?

Jesse

**Comment by jbhopkins** [comment]
So I think the second issue is an issue with the setup.py file not telling pip to copy over non python files. I've just pushed an update to the git that should fix that. Please grab the latest version of the code from the git and see if it works for you. Let me know if this fixes the issue.

(As an aside, I never encounter this because I always pip install in place, since I'm developing the code. It's only an issue if you do a normal pip install and, I think, then remove the folder it was installed from).

**Comment by dsclassen** [comment]
This seems to work. I can't remember why I was installing `pocl` to begin with. If I leave `pocl` out of my `environment.yml` file and install BioXTAS from the `main` branch on GitHub (rather than the 2.2.2.zip file). I get the following:

```python
Python 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 17:57:40) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bioxtasraw.RAWAPI as raw
WARNING:silx.opencl.common:The module pyOpenCL has been imported but can't be used here
>>> 
```

So there is a Warning, but I'm going to ignore that for now and hopefully all the BioXTAS tools I need will work as expected.

**Comment by jbhopkins** [comment]
pocl is pyOpenCl. You'd want it if you're using RAW to reduce images to .dat files, since pyFAI uses it to run that process on the GPU which is much faster than doing it on the CPU. Similarly the silx warning you're seeing about missing pyOpenCl would be fixed if you had it installed. But if you're not doing image reduction not having it shouldn't impact anything else.
